#!/bin/bash
set -e
SCRIPTDIR=$(readlink -f $(dirname "${BASH_SOURCE[0]}"))
SRCDIR=ext-src
STLSOFT_SRC=https://codeload.github.com/synesissoftware/STLSoft-1.9/zip/STLSoft-1.9.131
PANTHEIOS_SRC=https://downloads.sourceforge.net/project/pantheios/Pantheios%20%28C%20and%20Cxx%29/1.0.1%20%28beta%20216%29/pantheios-1.0.1-beta216.zip?use_mirror=autoselect
GTEST_SRC=https://github.com/google/googletest/archive/release-1.8.0.zip

STLSOFT_ARC=$(basename ${STLSOFT_SRC})
STLSOFT_NAME=${STLSOFT_ARC%.*}-${STLSOFT_ARC}
PANTHEIOS_ARC=$(basename ${PANTHEIOS_SRC})
PANTHEIOS_ARC=${PANTHEIOS_ARC%\?*}
PANTHEIOS_NAME=${PANTHEIOS_ARC%.zip}
GTEST_ARC=$(basename ${GTEST_SRC})
GTEST_NAME=googletest-${GTEST_ARC%.zip}

[[ -e ${SRCDIR} ]] || mkdir ${SRCDIR}
[[ -e ${SRCDIR}/${STLSOFT_ARC} ]] ||
    wget ${STLSOFT_SRC} -O ${SRCDIR}/${STLSOFT_ARC}.zip
[[ -e ${SRCDIR}/${PANTHEIOS_ARC} ]] ||
    wget ${PANTHEIOS_SRC} -O ${SRCDIR}/${PANTHEIOS_ARC}
[[ -e ${SRCDIR}/${GTEST_ARC} ]] ||
    wget ${GTEST_SRC} -O ${SRCDIR}/${GTEST_ARC}

unzip ${SRCDIR}/${STLSOFT_ARC}.zip
cp -r ${STLSOFT_NAME}/include/. include
export STLSOFT=$(readlink -f .)
sed -ie 's/__GNUC__ != 4/__GNUC__ < 4/' include/stlsoft/stlsoft.h
rm -rf ${STLSOFT_NAME}

unzip ${SRCDIR}/${PANTHEIOS_ARC}
pushd ${PANTHEIOS_NAME}
patch -p1 < "${SCRIPTDIR}"/pantheios/pantheios-1.0.1-file-mode.patch
VER=$(gcc -dumpversion | sed -e 's/\.\([^.]*\)\..*/\1/')
if [[ ${VER} -gt 47 ]]; then
    VER=47
fi
cd "build/gcc${VER}.unix.file64bit"
make CPPC_F_ADDITIONAL=-fPIC CC_F_ADDITIONAL=-fPIC CPPC_F_WARNING_ERR= CC_F_WARNING_ERR= build.libs
popd
cp -r ${PANTHEIOS_NAME}/include/. include
cp -r ${PANTHEIOS_NAME}/lib/. lib
echo "gcc${VER}" > lib/pantheios-ver
rm -rf ${PANTHEIOS_NAME}

unzip ${SRCDIR}/${GTEST_ARC}
pushd ${GTEST_NAME}
cmake googlemock
make
cp lib* ../lib
cp -r googlemock/include/. googletest/include/. ../include
popd
rm -rf ${GTEST_NAME}
