#!/bin/bash

### BEGIN INIT INFO
# Provides:          cpfs-data
# Required-Start:    $time $network
# Required-Stop:     $network
# Default-Start:
# Default-Stop:      0 1 2 6
# Short-Description: CPFS data server
# Description:       Run CPFS data server.  Configure it in
#                    /etc/default/cpfs-data
### END INIT INFO

. /lib/lsb/init-functions
NAME=cpfs-data
CONFIG_PATH=/etc/default/${NAME}
[[ -e ${CONFIG_PATH} ]] && . "${CONFIG_PATH}"
DAEMON=/usr/local/sbin/cpfs_server
[[ -x ${DAEMON} ]] || exit 5
PIDFILE=/var/run/${NAME}.pid

RETVAL=0

start_setup_args() {
    local ms ms_ip_port ms_idx local_ip role
    if [[ -z ${METADATA_SERVER} ]]; then
        echo "Please specify METADATA_SERVER in ${CONFIG_PATH}" >&2
        exit 1
    fi
    ms=(${METADATA_SERVER//,/ })
    ms_ip_port=(${ms[0]//:/ })
    local_ip=$(ip route get "${ms_ip_port[0]}" |
        head -n 1 | sed -e 's/.*src //' -e 's/ .*$//')
    if [[ -z ${DATA_DIR} ]]; then
        echo "Please specify DATA_DIR in ${CONFIG_PATH}" >&2
        exit 1
    fi
    DATA_DIR=$(readlink -m ${DATA_DIR})
    if [[ -z ${DS_PORT} ]]; then
        echo "Please specify DS_PORT in ${CONFIG_PATH}" >&2
        exit 1
    fi
    ARGS=(--meta-server="${METADATA_SERVER}" --role=DS
          --data="${DATA_DIR}"
          --ds-host="${DS_HOST:-${local_ip}}" --ds-port="${DS_PORT}"
          --log-level="${LOG_LEVEL:-5}"
          --log-path="${LOG_PATH:-/var/log/cpfs-data.log}"
          --daemonize=true --pidfile="${PIDFILE}"
          "${DS_EXTRA_ARGS[@]}")
}

log_msg() {
    local msg=$1
    local res=$2
    if [[ "${res}" = 0 ]]; then
        log_success_msg "${msg}"
    else
        log_failure_msg "${msg}"
    fi
}

case "$1" in
    start)
        start_setup_args
        start_daemon -p "${PIDFILE}" "${DAEMON}" "${ARGS[@]}"
        RETVAL=$?
        log_msg "Starting ${NAME}" ${RETVAL}
        ;;
    stop)
        killproc -p "${PIDFILE}" "${DAEMON}"
        RETVAL=$?
        log_msg "Stopping ${NAME}" ${RETVAL}
        ;;
    restart|reload)
        "$0" stop && sleep 2 && "$0" start
        RETVAL=$?
        ;;
    status)
        pidofproc -p "${PIDFILE}" "${DAEMON}" > /dev/null
        RETVAL=$?
        case ${RETVAL} in
          0)
            echo "${NAME} is running"
            ;;
          3)
            echo "${NAME} is not running"
            ;;
          *)
            echo "${NAME} is in unexpected state (${RETVAL})"
            ;;
        esac
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload|status}"
        exit 2
        ;;
esac

exit $RETVAL
